CODIFICAÇÃO/projeto/biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

CODIFICAÇÃO/projeto/biblioteca/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro", views.cadastro, name="cadastro"),
    path("listar", views.listar, name="listar"),
]

CODIFICAÇÃO/projeto/biblioteca/core/models.py
from djongo import models


class LivroModel(models.Model):
    titulo = models.CharField("Título", max_length=200)
    editora = models.CharField("editora", max_length=200)
    nome = models.CharField(null=True, max_length=100)
    categoria = models.CharField(null=True, max_length=50)
    quantidade = models.IntegerField(null=True)
    validade = models.DateField(null=True)
    objects = models.Manager()

    def __str__(self):
        return self.titulo

CODIFICAÇÃO/projeto/biblioteca/core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from core.models import LivroModel


def validate_title(value):
    if len(value) < 10:
        raise ValidationError("Deve ter pelo menos dez caracteres")


class LivroForm(forms.ModelForm):
    class Meta:
        model = LivroModel
        fields = ["nome", "categoria", "quantidade", "validade"]
        error_messages = {
            "nome": {
                "required": ("Informe o nome a ser cadastrado."),
            },
            "quantidade": {
                "required": ("Informe a quantidade"),
            },
            "validade": {
                "required": ("Informe a validade"),
            },
        }

    def clean_titulo(self):
        titulo = self.cleaned_data["titulo"]
        validate_title(titulo)
        return titulo

    def clean_editora(self):
        editora = self.cleaned_data["editora"]
        validate_title(editora)
        return editora

    def clean_nome(self):
        nome = self.cleaned_data["nome"]
        validate_title(nome)
        return nome

    # def clean_categoria(self):
    #     categoria = self.cleaned_data["categoria"]
    #     validate_title(categoria)
    #     return categoria

    def clean_quantidade(self):
        quantidade = self.cleaned_data["quantidade"]
        validate_title(quantidade)
        return quantidade

    def clean_vencimento(self):
        vencimento = self.cleaned_data["vencimento"]
        validate_title(vencimento)
        return vencimento

    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data

CODIFICAÇÃO/projeto/biblioteca/core/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .forms import LivroForm
from .models import LivroModel


def index(request):
    foods = LivroModel.objects.all()
    return render(request, "index.html", {"foods": foods})
    # if request.method == 'GET':
    #     return render(request, "index.html")
    # else:
    #     return HttpResponseRedirect(reverse('core:index'))


def cadastro(request):
    if request.method == "POST":
        form_livro = LivroForm(request.POST)
        if form_livro.is_valid():
            eleitor = LivroModel.objects.create(**form_livro.cleaned_data)
            return HttpResponseRedirect(reverse("core:index"))
        else:
            contexto = {"formulario_livro": form_livro}
            return render(request, "cadastro.html", contexto)
    else:
        contexto = {"formulario_livro": LivroForm()}
        return render(request, "cadastro.html", contexto)


def listar(request):
    if request.method == "POST":
        livro_id = request.POST.get("livro_id", "")
        try:
            livro = LivroModel.objects.get(pk=livro_id)
            contexto = {"livro": livro}
        except ValueError:
            contexto = {}
        return render(request, "detalhes.html", contexto)
    else:
        livros = LivroModel.objects.all()
        contexto = {"livros": livros}
        return render(request, "listar.html", contexto)

CODIFICAÇÃO/projeto/biblioteca/core/templates/cadastro.html
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Biblioteca</title>
</head>

<body>
    <header>
        <h1>Biblioteca</h1>
        <h2>Cadastro de Livros</h2>
    </header>

    <form action="{% url 'core:cadastro' %}" novalidate method="POST" enctype="multipart/form-data">
        <br>
        {% csrf_token %}
        <div class="form-field">
            <label for="{{ formulario_livro.titulo.id_for_label }}">Título:</label>
            <input> {{ formulario_livro.nome }}</input>
        </div>
        <br>
        <div class="form-field">
            <label for="{{ formulario_livro.editora.id_for_label }}">Quantidade:</label>
            {{ formulario_livro.quantidade }}
        </div>
        <br>
        <div class="form-field">
            <label for="{{ formulario_livro.editora.id_for_label }}">Autor:</label>
            {{ formulario_livro.autor }}
        </div>
        <br>
        <div class="form-field">
            <label for="{{ formulario_livro.editora.id_for_label }}">ISBN:</label>
            {{ formulario_livro.isbn }}
        </div>
        <br>
        <div class="form-field">
            <label for="{{ formulario_livro.editora.id_for_label }}">Numero de Paginas:</label>
            {{ formulario_livro.numero_paginas }}
        </div>
        <br>
        <div class="form-field">
            <label for="{{ formulario_livro.editora.id_for_label }}">Ano de escria da obra:</label>
            {{ formulario_livro.ano }}
        </div>
        <br>
        <div class="form-actions">
            <center>
                <input type="submit" value="Cadastrar">
            </center>
        </div>
    </form>
    <br><br>
    {% if formulario_livro.errors %}
    <div class="form-errors">
        {% for field in formulario_livro %}
        {% for error in field.errors %}
        <strong>{{ error|escape }}</strong><br>
        {% endfor %}
        {% endfor %}
    </div>
    {% endif %}

    <div class="form-actions">
        <center>
            <form action="{% url 'core:index' %}" novalidate method="GET">
                <input type="submit" value="Voltar">
            </form>
        </center>
    </div>
</body>

</html>

CODIFICAÇÃO/projeto/biblioteca/core/templates/detalhes.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
        <br>

        {% if livro %}
            <h2> Detalhes de um livro selecionado </h2>
            <h3>
                Livro :  {{ livro.titulo }}
                <br><br>
                Editora : {{ livro.editora }}
            </h3>
        <br><br>
        {% else %}
            <h2> Nenhum livro cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:listar' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>

CODIFICAÇÃO/projeto/biblioteca/core/templates/listar.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Orlando Saraiva do Nascimento Júnior">
        <link rel="stylesheet" href="{% static '/css/style.css' %}">
        <title>Biblioteca</title>
    </head>
    <body>
        <br>
            <h1> Biblioteca </h1>
            <h2> Listar os livros cadastrados </h2>
        <br>

        {% if livros %}
            <h3>Livros Cadastrados</h3>
            {% for livro in livros %}
                <form action={% url 'core:listar' %} novalidate method="POST" enctype="multipart/form-data">
                    {% csrf_token %}        
                    Livro: {{ livro }}
                    <input type="hidden" name="livro_id" value={{ livro.pk }}>        
                    <input type="submit" value="Detalhes"/>              
                </form>
            {% endfor %}
        {% else %}
            <h2> Nenhum livro cadastrado </h2>      
        {% endif %} 

        <center>
            <form action={% url 'core:index' %} novalidate method="GET">
                <input type="submit" value="Voltar"/>              
            </form>
        </center>
    </body>

</html>